import fs from 'node:fs';
import path from 'node:path';

import type { Plugin } from 'vite';

/**
 * Phase C / Task C5 — the build-time app-source manifest plugin.
 *
 * It resolves the virtual module {@link VIRTUAL_ID}, generating a manifest that
 * STATICALLY imports every app source file under `<appDir>/src` and
 * `<appDir>/config` (so Rolldown INLINES them into `dist/server.js`) and exposes:
 *
 *   - `files`    — absolute paths of every inlined file (drives loader DISCOVERY),
 *   - `load`     — async getter (backs `strapi.importModule`),
 *   - `loadSync` — sync getter (used by the synchronous config loader).
 *
 * The discovery globs mirror Strapi's loaders: `src/index.*`, `src/api/**`
 * (controllers/services/routes/policies/middlewares/config + content-type
 * `schema.json`), `src/policies/**`, `src/middlewares/**`, and `config/**`.
 *
 * Off-path (dev, JS-disk prod) this plugin is never registered — the virtual
 * module is unused and the loaders keep their disk-based discovery.
 */
export const VIRTUAL_ID = 'virtual:strapi-app-manifest';
const RESOLVED_VIRTUAL_ID = `\0${VIRTUAL_ID}`;

// File extensions the loaders accept for app source + content schemas.
const SOURCE_EXTS = new Set(['.js', '.ts', '.mts', '.cts', '.mjs', '.cjs', '.json']);

// Directories under the app that the loaders discover. Anything outside these
// is left to disk (e.g. the admin client graph, public assets).
const scanRoots = (appDir: string): string[] => [
  path.join(appDir, 'src'),
  path.join(appDir, 'config'),
];

const walk = (dir: string, acc: string[] = []): string[] => {
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return acc; // dir absent — skip
  }
  for (const entry of entries) {
    if (entry.name.startsWith('.')) {
      continue;
    }
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full, acc);
    } else if (SOURCE_EXTS.has(path.extname(entry.name))) {
      acc.push(full);
    }
  }
  return acc;
};

/** Collect every inlinable app source file, deterministically ordered. */
export const collectAppSourceFiles = (appDir: string): string[] =>
  scanRoots(appDir)
    .flatMap((root) => walk(root))
    .sort();

/** Generate the manifest module source for a set of absolute file paths. */
export const generateManifestSource = (files: string[]): string => {
  const imports = files
    .map((abs, i) => `import * as m${i} from ${JSON.stringify(abs)};`)
    .join('\n');

  const map = files.map((abs, i) => `  ${JSON.stringify(abs)}: m${i},`).join('\n');

  return `// AUTO-GENERATED by @strapi/strapi app-manifest-plugin. Do not edit.
${imports}

const MODULES = {
${map}
};

const FILES = ${JSON.stringify(files)};

function pick(absPath) {
  const mod = MODULES[absPath];
  if (mod === undefined) {
    throw new Error('[strapi] app manifest: module not inlined: ' + absPath);
  }
  return mod;
}

export const manifest = {
  files: FILES,
  load: (absPath) => Promise.resolve(pick(absPath)),
  loadSync: (absPath) => pick(absPath),
};

export default manifest;
`;
};

export const appManifestPlugin = (appDir: string): Plugin => ({
  name: 'strapi:app-manifest',
  resolveId(id) {
    if (id === VIRTUAL_ID) {
      return RESOLVED_VIRTUAL_ID;
    }
    return null;
  },
  load(id) {
    if (id === RESOLVED_VIRTUAL_ID) {
      const files = collectAppSourceFiles(appDir);
      return generateManifestSource(files);
    }
    return null;
  },
});
